# Generated by Django 5.1.1 on 2024-11-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="range",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
