# Generated by Django 5.1.1 on 2024-11-09 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "carrent",
            "0003_remove_vehicle_position_x_remove_vehicle_position_y_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="endlocation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="end_rentals",
                to="carrent.location",
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="startlocation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="start_rentals",
                to="carrent.location",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="position_x",
            field=models.FloatField(default="0"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="position_y",
            field=models.FloatField(default="0"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="carrent.location",
            ),
        ),
    ]
